### ISSUE TITLE
hal component push is failing

### ISSUE THREAD

**Issue by cmoulliard** [halkyonio/hal#20] opened 2019-09-10 17:38 UTC
## Issue

Hal version : v0.1.4

If we have previously deploy the components and we re-deploy then that fails

```
hal component push -c fruit-client-sb,fruit-backend-sb
 ✓  Uploading /Users/dabou/Temp/rhtelab/fruit-client-sb/target/fruit-client-sb-1.0.0-SNAPSHOT.jar
 ✗  Uploading /Users/dabou/Temp/rhtelab/fruit-backend-sb/target/fruit-backend-sb-1.0.0-SNAPSHOT.jar
FATA[0063] error running push: error uploading jar: exit status 1 

hal component push -c fruit-client-sb,fruit-backend-sb
No local changes detected for 'fruit-client-sb' component: nothing to push!
 ✗  Uploading /Users/dabou/Temp/rhtelab/fruit-backend-sb/target/fruit-backend-sb-1.0.0-SNAPSHOT.jar
FATA[0005] error running push: error uploading jar: exit status 1 
```

**Comment by cmoulliard** [comment] 2019-09-10 17:49
If I delete from the `fruit-client-sb,fruit-backend-sb` pods, the jar uploaded within the pod and re-execute next the command, then that works correctly.

**Comment by metacosm** [comment] 2019-09-10 20:35
Can you add more details on how to reproduce this issue because I haven't been able to so far…

**Comment by cmoulliard** [comment] 2019-09-11 08:52
Here is the scenario I played - successfully this morning

```
hal version: hal version
hal v0.1.4-1-g0abdaf4
halkyon-operator git commit: 6e521cb5


oc login --token=FHCHfT3paTXJieBwV5YNCSjFWWN4LBknyhm7DjPmvdg --server=https://api.cluster-416e.416e.sandbox352.opentlc.com:6443
oc delete project rhtelab
oc new-project rhtelab

mkdir rhtelab && cd rhtelab
hal component spring-boot \
   -i fruit-client-sb \
   -g me.fruitsand \
   -p me.fruitsand.demo \
   -s 2.1.6.RELEASE \
   -t client \
   -v 1.0.0-SNAPSHOT \
   --supported=false  \
  fruit-client-sb

hal component spring-boot \
   -i fruit-backend-sb \
   -g me.fruitsand \
   -p me.fruitsand.demo \
   -s 2.1.6.RELEASE \
   -t crud \
   -v 1.0.0-SNAPSHOT \
   --supported=false  \
  fruit-backend-sb

mvn clean package -f fruit-client-sb
mvn clean package -f fruit-backend-sb -Pkubernetes

hal component push -c fruit-client-sb,fruit-backend-sb
'fruit-client-sb' component was not found, initializing it
 ✓  Waiting for component fruit-client-sb to be ready…
 ✓  Uploading /Users/dabou/Temp/rhtelab/fruit-client-sb/target/fruit-client-sb-1.0.0-SNAPSHOT.jar
'fruit-backend-sb' component was not found, initializing it
 ✓  Waiting for component fruit-backend-sb to be ready…
 ✓  Uploading /Users/dabou/Temp/rhtelab/fruit-backend-sb/target/fruit-backend-sb-1.0.0-SNAPSHOT.jar


hal capability
? Category database
? Type postgres
? Version 10
? Change default name postgres-db
? Enter a value for string property DB_NAME: sample-db
? Enter a value for string property DB_PASSWORD: admin
? Enter a value for string property DB_USER: admin
 ✓  Created capability postgres-db


hal link
? Target component: fruit-backend-sb
? Use Secret Yes
? Secret postgres-db-config
? Change default name backend-to-db
 ✓  Created link backend-to-db


hal link
? Target component: fruit-client-sb
? Use Secret No
? Env variable in the 'name=value' format, press enter when done KUBERNETES_ENDPOINT_FRUIT=http://fruit-backend-sb:8080/api/fruits
Set env variable: KUBERNETES_ENDPOINT_FRUIT=http://fruit-backend-sb:8080/api/fruits
? Env variable in the 'name=value' format, press enter when done 
? Change default name client-to-backend
 ✓  Created link client-to-backend
```

**Comment by metacosm** [comment] 2019-09-11 08:54
So do you have an issue or not? 😄 
If not, please close the issue.

**Comment by cmoulliard** [comment] 2019-09-11 08:55
As I can't reproduce it anymore. We will close it

**Comment by cmoulliard** [comment] 2019-09-28 09:11
Here is the scenario tested against this ocp3 instance: `https://116.203.87.224:8443/console/` and `hal component push -c fruit-client-sb` pushes fail using:

```
hal version
hal v0.1.9-4-gb3778c2 built with ❤️ by the Halkyon team on 'Sat Sep 28 09:35:21 CEST 2019' (commit: b3778c2) running on top of 'oc
```

Pods, components status
```
oc get cp
NAME               RUNTIME       VERSION         AGE       MODE      STATUS    MESSAGE   REVISION
fruit-backend-sb   spring-boot   2.1.6.RELEASE   7m        dev       Ready     Ready
fruit-client-sb    spring-boot   2.1.6.RELEASE   7m        dev       Ready     Ready

hal component push -c fruit-client-sb
Local changes detected for 'fruit-client-sb' component: about to push source code to remote cluster
 ✗  Uploading /Users/dabou/Temp/test/fruit-client-sb.tar
 ✗  error running push: error uploading file: exit status 2

oc get pods
NAME                               READY     STATUS    RESTARTS   AGE
fruit-backend-sb-c7bd69b4-f98q5    1/1       Running   0          7m
fruit-client-sb-7554798795-nhgmq   1/1       Running   0          7m
postgres-db-0                      1/1       Running   0          7m
```

Steps to reproduce 

```
cd ~/Temp
echo "########################"
echo "#### Create Test project"
echo "########################"
mkdir test && cd test

echo "########################"
echo "#### Create Pom parent file"
echo "########################"
cat <<EOF > pom.xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>me.fruitstand</groupId>
    <artifactId>parent</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <name>Spring Boot - Demo</name>
    <description>Spring Boot - Demo</description>
    <packaging>pom</packaging>
    <modules>
        <module>fruit-backend-sb</module>
        <module>fruit-client-sb</module>
    </modules>
</project>
EOF

echo "########################"
echo "#### Scaffold projects"
echo "########################"

hal component spring-boot \
   -i fruit-backend-sb \
   -g me.fruitsand \
   -p me.fruitsand.demo \
   -s 2.1.6.RELEASE \
   -t crud \
   -v 1.0.0-SNAPSHOT \
   --supported=false  \
   fruit-backend-sb

 hal component spring-boot \
   -i fruit-client-sb \
   -g me.fruitsand \
   -p me.fruitsand.demo \
   -s 2.1.6.RELEASE \
   -t client \
   -v 1.0.0-SNAPSHOT \
   --supported=false  \
   fruit-client-sb  

echo "########################"
echo "#### Maven package"
echo "########################"
mvn package -f fruit-client-sb
mvn package -f fruit-backend-sb -Pkubernetes

echo "########################"
echo "#### Create component"
echo "########################"
hal component create -c fruit-client-sb
hal component create -c fruit-backend-sb

echo "########################"
echo "#### Create Capability"
echo "########################"
#hal capability create -n postgres-db -g database -t postgres -v 10 -p DB_NAME=sample-db -p DB_PASSWORD=admin -p DB_USER=admin
cat <<EOF | kubectl apply -f -
apiVersion: halkyon.io/v1beta1
kind: Capability
metadata:
  name: postgres-db
spec:
  category: Database
  parameters:
  - name: DB_NAME
    value: sample-db
  - name: DB_PASSWORD
    value: admin
  - name: DB_USER
    value: admin
  type: Postgres
  version: "10"
EOF

echo "########################"
echo "#### Link"
echo "########################"
hal link create -n backend-to-db -t fruit-backend-sb -s postgres-db-config
hal link create -n client-to-backend -t fruit-client-sb -e KUBERNETES_ENDPOINT_FRUIT=http://fruit-backend-sb:8080/api/fruits

echo "########################"
echo "#### Push"
echo "########################"
sleep 60s

#hal component push -c fruit-client-sb
PROJECT=fruit-client-sb
NAMESPACE=test
POD_ID=$(oc get pod -lapp=$PROJECT -n $NAMESPACE -o name | awk -F '/' '{print $2}')
oc cp $PROJECT/pom.xml $POD_ID:/usr/src/ -n $NAMESPACE
oc cp $PROJECT/src $POD_ID:/usr/src/ -n $NAMESPACE
oc exec $POD_ID -n $NAMESPACE /var/lib/supervisord/bin/supervisord ctl start build
oc exec $POD_ID -n $NAMESPACE /var/lib/supervisord/bin/supervisord ctl start run

#hal component push -c fruit-backend-sb
PROJECT=fruit-backend-sb
NAMESPACE=test
POD_ID=$(oc get pod -lapp=$PROJECT -n $NAMESPACE -o name | awk -F '/' '{print $2}')
oc cp $PROJECT/pom.xml $POD_ID:/usr/src/ -n $NAMESPACE
oc cp $PROJECT/src $POD_ID:/usr/src/ -n $NAMESPACE
oc exec $POD_ID -n $NAMESPACE /var/lib/supervisord/bin/supervisord ctl start build
oc exec $POD_ID -n $NAMESPACE /var/lib/supervisord/bin/supervisord ctl start run

echo "########################"
echo "#### Wait and call endpoint"
echo "########################"
sleep 120s
FRONTEND_URL=$(oc get routes/fruit-client-sb --template={{.spec.host}})
curl "http://${FRONTEND_URL}/api/client"

echo "########################"
echo "#### Delete"
echo "########################"
oc delete all --all
cd .. && rm -rf test
```

**Comment by cmoulliard** [comment] 2019-09-28 10:42
Question: Is it the plan to upload the tar file of the code source using this path `/usr/component.tar` ? If this is the case, are you sure that the pod's user has write/exec access ? @metacosm 

```
$ ls -la /usr
total 44
drwxr-xr-x. 1 root root 4096 Sep 10 00:00 .
drwxr-xr-x. 1 root root 4096 Sep 28 09:05 ..
drwxr-xr-x. 1 root root 4096 Sep 14 02:33 bin
drwxr-xr-x. 2 root root 4096 Aug 30 12:31 games
drwxr-xr-x. 2 root root 4096 Aug 30 12:31 include
drwxr-xr-x. 1 root root 4096 Sep 14 02:33 lib
drwxr-xr-x. 1 root root 4096 Sep 14 00:24 local
drwxr-xr-x. 1 root root 4096 Sep 14 00:24 sbin
drwxr-xr-x. 1 root root 4096 Sep 14 02:33 share
drwxrwx---. 4 root root 4096 Sep 28 09:06 src
$ ls -la /usr/src
total 16424
drwxrwx---. 4 root       root     4096 Sep 28 09:06 .
drwxr-xr-x. 1 root       root     4096 Sep 10 00:00 ..
-rw-r--r--. 1 1000190000 root 16796946 Sep 28 09:06 app.jar
-rw-r--r--. 1 1000190000 root     3055 Sep 28 09:04 pom.xml
drwxr-xr-x. 3 1000190000 root     4096 Sep 28 09:06 src
drwxr-xr-x. 6 1000190000 root     4096 Sep 28 09:06 target
```

**Comment by cmoulliard** [comment] 2019-09-28 10:48
The problem is fixed if you upload the `/usr/component.tar` of the source under `/usr/src/component.tar` ;-) @metacosm

**Closed as completed** 2019-09-28 11:17 UTC
Labels: bug
